"""add_cashier_and_discount

Revision ID: 206f84b8ee46
Revises: b3f8a9c2b4de
Create Date: 2026-06-05 10:46:23.132587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206f84b8ee46'
down_revision: Union[str, Sequence[str], None] = 'b3f8a9c2b4de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('cashier_name', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('cashier_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'cashier_name')
    op.drop_column('invoices', 'cashier_name')
    # ### end Alembic commands ###
