"""Refactor measurement schema JSONB

Revision ID: 2bf1a513987e
Revises: 6cf8bd61d2c5
Create Date: 2026-05-27 09:12:44.195131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bf1a513987e'
down_revision: Union[str, Sequence[str], None] = '6cf8bd61d2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('measurements_template_id_fkey'), 'measurements', type_='foreignkey')
    op.drop_index(op.f('ix_measurement_templates_dress_type'), table_name='measurement_templates')
    op.drop_index(op.f('ix_measurement_templates_id'), table_name='measurement_templates')
    op.drop_table('measurement_templates')
    op.add_column('measurements', sa.Column('measurement_code', sa.String(), nullable=False))
    op.add_column('measurements', sa.Column('dress_type', sa.String(), nullable=False))
    op.add_column('measurements', sa.Column('measurement_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('measurements', sa.Column('reference_image_url', sa.String(), nullable=True))
    op.add_column('measurements', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('measurements', sa.Column('is_used_in_order', sa.Boolean(), nullable=True))
    op.alter_column('measurements', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_measurement_customer_dress', 'measurements', ['customer_id', 'dress_type'], unique=False)
    op.create_index(op.f('ix_measurements_dress_type'), 'measurements', ['dress_type'], unique=False)
    op.create_index(op.f('ix_measurements_measurement_code'), 'measurements', ['measurement_code'], unique=True)
    op.drop_column('measurements', 'data')
    op.drop_column('measurements', 'images')
    op.drop_column('measurements', 'template_id')
    op.drop_column('measurements', 'alteration_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('alteration_notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('measurements', sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('measurements', sa.Column('images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('measurements', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('measurements_template_id_fkey'), 'measurements', 'measurement_templates', ['template_id'], ['id'])
    op.drop_index(op.f('ix_measurements_measurement_code'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_dress_type'), table_name='measurements')
    op.drop_index('ix_measurement_customer_dress', table_name='measurements')
    op.alter_column('measurements', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('measurements', 'is_used_in_order')
    op.drop_column('measurements', 'notes')
    op.drop_column('measurements', 'reference_image_url')
    op.drop_column('measurements', 'measurement_data')
    op.drop_column('measurements', 'dress_type')
    op.drop_column('measurements', 'measurement_code')
    op.create_table('measurement_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dress_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('measurement_templates_pkey'))
    )
    op.create_index(op.f('ix_measurement_templates_id'), 'measurement_templates', ['id'], unique=False)
    op.create_index(op.f('ix_measurement_templates_dress_type'), 'measurement_templates', ['dress_type'], unique=True)
    # ### end Alembic commands ###
