"""add_telegram_chat_id_and_outbox

Revision ID: 6bb6592bb0ca
Revises: 6dfb19b08504
Create Date: 2026-06-08 10:47:54.794181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb6592bb0ca'
down_revision: Union[str, Sequence[str], None] = '6dfb19b08504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.Column('message_body', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('log_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_outbox_id'), 'notification_outbox', ['id'], unique=False)
    op.add_column('customers', sa.Column('telegram_chat_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'telegram_chat_id')
    op.drop_index(op.f('ix_notification_outbox_id'), table_name='notification_outbox')
    op.drop_table('notification_outbox')
    # ### end Alembic commands ###
