"""Update customer schema for shared contacts

Revision ID: 6cf8bd61d2c5
Revises: 6d5445bc2bfd
Create Date: 2026-05-27 07:09:43.572372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf8bd61d2c5'
down_revision: Union[str, Sequence[str], None] = '6d5445bc2bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('customer_code', sa.String(), nullable=False))
    op.add_column('customers', sa.Column('contact_number', sa.String(), nullable=False))
    op.add_column('customers', sa.Column('alternate_contact', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_customers_mobile_number'), table_name='customers')
    op.create_index(op.f('ix_customers_contact_number'), 'customers', ['contact_number'], unique=False)
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=True)
    op.drop_column('customers', 'mobile_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('mobile_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.drop_index(op.f('ix_customers_contact_number'), table_name='customers')
    op.create_index(op.f('ix_customers_mobile_number'), 'customers', ['mobile_number'], unique=True)
    op.drop_column('customers', 'is_active')
    op.drop_column('customers', 'alternate_contact')
    op.drop_column('customers', 'contact_number')
    op.drop_column('customers', 'customer_code')
    # ### end Alembic commands ###
