"""add columns to staff table

Revision ID: 6dfb19b08504
Revises: 206f84b8ee46
Create Date: 2026-06-05 09:48:02.542156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dfb19b08504'
down_revision: Union[str, Sequence[str], None] = '206f84b8ee46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('measurements', 'measurement_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.add_column('staff', sa.Column('mobile_number', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('salary', sa.Float(), nullable=True))
    op.add_column('staff', sa.Column('commission_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'commission_rate')
    op.drop_column('staff', 'salary')
    op.drop_column('staff', 'mobile_number')
    op.alter_column('measurements', 'measurement_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
