"""Add paid and balance amount to invoice

Revision ID: accf9a7d6bee
Revises: 2bf1a513987e
Create Date: 2026-05-27 09:30:24.849583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'accf9a7d6bee'
down_revision: Union[str, Sequence[str], None] = '2bf1a513987e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('paid_amount', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('balance_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'balance_amount')
    op.drop_column('invoices', 'paid_amount')
    # ### end Alembic commands ###
