"""Add student_admission_no

Revision ID: ad46c83f3519
Revises: accf9a7d6bee
Create Date: 2026-05-28 05:57:34.068062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad46c83f3519'
down_revision: Union[str, Sequence[str], None] = 'accf9a7d6bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('student_admission_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'student_admission_no')
    # ### end Alembic commands ###
