"""add finance stafftype

Revision ID: b0337cf09ff9
Revises: f9b6d4720358
Create Date: 2026-06-15 09:09:15.597430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0337cf09ff9'
down_revision: Union[str, Sequence[str], None] = 'f9b6d4720358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add FINANCE to PostgreSQL enum type stafftype
    op.execute("ALTER TYPE stafftype ADD VALUE 'FINANCE'")



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
